export enum ReasonsEnum {
  USER_REQUESTED = 'USER_REQUESTED',
  RECONCILIATION = 'RECONCILIATION',
  ACCOUNT_CLOSURE = 'ACCOUNT_CLOSURE',
  ENTRY_INACTIVITY = 'ENTRY_INACTIVITY',
  FRAUD = 'FRAUD',
}
